name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - master

jobs:
  pre-cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pre-clean Disk Space
      run: |
        # Clean up Docker images and containers
        docker stop $(docker ps -aq) || true
        docker rm $(docker ps -aq) || true
        docker rmi $(docker images -aq) || true
        docker system prune -af --volumes || true

        # Clean up apt cache
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        
        # Clean up npm cache
        npm cache clean --force || true
        
        # Show disk space usage
        df -h

  build:
    runs-on: ubuntu-latest
    needs: pre-cleanup  # Execute after pre-cleanup job
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dos2unix
      run: sudo apt-get install -y dos2unix

    - name: Setup SSH Key
      env:
        KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$KEY" > private_key.pem
        sudo chmod 600 private_key.pem
        dos2unix private_key.pem

    - name: Ensure SSH folder exists and add EC2 to known hosts
      env:
        HOST: ${{ secrets.EC2_HOST }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

    - name: Install libcrypto
      run: sudo apt-get update && sudo apt-get install -y libssl-dev

    - name: Copy files to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        scp -i private_key.pem docker-compose.yml $USER@$HOST:/home/$USER/
        if [ -f .env ]; then
          scp -i private_key.pem .env $USER@$HOST:/home/$USER/
        fi

    - name: Fix Docker permissions
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -i private_key.pem $USER@$HOST << 'EOF'
          sudo usermod -aG docker $USER
          sudo chmod 666 /var/run/docker.sock
        EOF

    - name: Install Docker and Docker Compose on EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -i private_key.pem $USER@$HOST << 'EOF'
          sudo yum update -y
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker

          # Install Docker Compose if not present
          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          else
            echo "Docker Compose is already installed."
          fi
        EOF

    - name: Build and Push Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t fastapi-app .
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        docker tag fastapi-app $DOCKER_USER/fastapi-app:latest
        docker push $DOCKER_USER/fastapi-app:latest

    - name: Deploy on EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -i private_key.pem $USER@$HOST << 'EOF'
          cd /home/$USER/
          sudo docker-compose down
          sudo docker-compose up -d --build
        EOF

    - name: Clean up
      run: rm -f private_key.pem